### ISSUE TITLE
请问您是如何用vue router实现从默认页面触发事件，路由至默认页面的兄弟页面

### ISSUE THREAD

**Issue by LouisaNikita** [vingojw/vue-vueRoute-webpack#2]
如您在项目http://m.yaomaiche.com中实现的，从首页点击车辆简介，便 路由至 车辆详情这个兄弟组件的界面中~
之前看到的例子一直是父组件中多个链接，分别指向子组件~没有在子组件中触发，向另一子组件的切换的这种~我考虑过路由至父组件，再从父组件指向目标子组件，可是没找到实现方法~
请问您是如何实现这种转换的？

**Comment by vingojw** [comment]
使用的是vue-router  , 首页（home.vue）和车辆详情页（product.vue）两个组件其实是平级的。比如首页是路由的 home.vue 组件， 当你在首页点击一辆车的时候，路由切换至 product.vue, 并通过 拿到 $route.params 里面的id 去找具体信息。    详细情况可以去看下[vue-router文档](http://router.vuejs.org/zh-cn/named.html)
